receivers:
  oltp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
exporters:
  oltp:
    endpoint: otelcol:4317
service:
  pipelines:
    traces:
      receivers: [oltp]
      processors: [batch]
      exporters: [oltp]
  